# numpy =numerical python 

In [2]:
!pip install numpy

Defaulting to user installation because normal site-packages is not writeable
   ---------------------------------------- 0.0/12.8 MB ? eta -:--:--
   ---------------------------------------- 0.0/12.8 MB ? eta -:--:--
    --------------------------------------- 0.3/12.8 MB ? eta -:--:--
   -- ------------------------------------- 0.8/12.8 MB 1.7 MB/s eta 0:00:08
   ---- ----------------------------------- 1.3/12.8 MB 1.9 MB/s eta 0:00:06
   ----- ---------------------------------- 1.8/12.8 MB 2.0 MB/s eta 0:00:06
   ------- -------------------------------- 2.4/12.8 MB 2.1 MB/s eta 0:00:05
   --------- ------------------------------ 2.9/12.8 MB 2.1 MB/s eta 0:00:05
   ---------- ----------------------------- 3.4/12.8 MB 2.2 MB/s eta 0:00:05
   ------------- -------------------------- 4.2/12.8 MB 2.3 MB/s eta 0:00:04
   ------------- -------------------------- 4.5/12.8 MB 2.3 MB/s eta 0:00:04
   --------------- ------------------------ 5.0/12.8 MB 2.2 MB/s eta 0:00:04
   ----------------


[notice] A new release of pip is available: 25.2 -> 25.3
[notice] To update, run: C:\Users\admin\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\python.exe -m pip install --upgrade pip


In [3]:
import numpy as np

In [4]:
# onedarray

In [5]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [6]:
np.ones(4,dtype=int)

array([1, 1, 1, 1])

In [8]:
np.zeros(5,dtype=int)

array([0, 0, 0, 0, 0])

In [9]:
# twodarray

In [10]:
np.ones((3,3),dtype=int)

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [11]:
np.zeros((4,4),dtype=int)

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [12]:
# multidimension array 

In [16]:
np.ones((4,2,2))

array([[[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]]])

In [17]:
# Generating Data Through Numpy

In [26]:
data=np.arange(2,38,3)

In [27]:
data

array([ 2,  5,  8, 11, 14, 17, 20, 23, 26, 29, 32, 35])

In [30]:
A=data.reshape(4,3)

In [31]:
A

array([[ 2,  5,  8],
       [11, 14, 17],
       [20, 23, 26],
       [29, 32, 35]])

In [ ]:
np.sum(A)

np.int64(222)

In [35]:
np.mean(A)

np.float64(18.5)

In [36]:
np.prod(A)

np.int64(81359229952000)

In [37]:
np.min(A)

np.int64(2)

In [38]:
np.max(A)

np.int64(35)

In [39]:
np.std(A)

np.float64(10.35615758860399)

In [40]:
# linespace=for equal distribution of numbers

In [42]:
np.linspace(2,10,4)

array([ 2.        ,  4.66666667,  7.33333333, 10.        ])

In [44]:
np.linspace(1,10,5)

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [45]:
# Generating random numbers in numpy

In [50]:
np.random.random(10)*100

array([50.6278068 , 27.92114181, 95.22937309, 31.7611563 ,  6.15702192,
       94.12250224, 18.23355151, 42.4411199 , 30.26220572, 58.9866183 ])

In [64]:
np.random.randint(1,10,12)

array([1, 8, 2, 3, 7, 5, 1, 5, 1, 8, 5, 5], dtype=int32)

In [65]:
np.random.normal(1,1,5)

array([0.23899965, 1.07665685, 0.37471663, 2.97554844, 0.09466188])

In [66]:
A

array([[ 2,  5,  8],
       [11, 14, 17],
       [20, 23, 26],
       [29, 32, 35]])

In [67]:
# Common functions in numpy

In [68]:
np.sqrt(A)

array([[1.41421356, 2.23606798, 2.82842712],
       [3.31662479, 3.74165739, 4.12310563],
       [4.47213595, 4.79583152, 5.09901951],
       [5.38516481, 5.65685425, 5.91607978]])

In [69]:
np.cos(A)

array([[-0.41614684,  0.28366219, -0.14550003],
       [ 0.0044257 ,  0.13673722, -0.27516334],
       [ 0.40808206, -0.53283302,  0.64691932],
       [-0.74805753,  0.83422336, -0.90369221]])

In [70]:
np.tan(A)

array([[  -2.18503986,   -3.38051501,   -6.79971146],
       [-225.95084645,    7.24460662,    3.49391565],
       [   2.23716094,    1.58815308,    1.17875355],
       [   0.88714284,    0.66100604,    0.47381472]])

In [71]:
A

array([[ 2,  5,  8],
       [11, 14, 17],
       [20, 23, 26],
       [29, 32, 35]])

In [ ]:
np.exp(A)
(2.71828)^2
(2.71828)^5

array([[7.38905610e+00, 1.48413159e+02, 2.98095799e+03],
       [5.98741417e+04, 1.20260428e+06, 2.41549528e+07],
       [4.85165195e+08, 9.74480345e+09, 1.95729609e+11],
       [3.93133430e+12, 7.89629602e+13, 1.58601345e+15]])